// Code generated by protoc-gen-easyrpc-rust. DO NOT EDIT.
pub fn method_specs() -> Vec<crate::protocol::MethodSpec> {
  vec![
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "Health".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/Health".to_string(), http_method: "POST".to_string(), client_stream: false, server_stream: false, body: String::new() },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "Echo".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/Echo".to_string(), http_method: "POST".to_string(), client_stream: false, server_stream: false, body: String::new() },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "Count".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/Count".to_string(), http_method: "POST".to_string(), client_stream: false, server_stream: true, body: String::new() },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "Fail".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/Fail".to_string(), http_method: "POST".to_string(), client_stream: false, server_stream: false, body: String::new() },
  ]
}
