// Code generated by protoc-gen-easyrpc-rust. DO NOT EDIT.
pub fn method_specs() -> Vec<crate::protocol::MethodSpec> {
  vec![
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "Health".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/Health".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "Echo".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/Echo".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "Count".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/Count".to_string(), client_stream: false, server_stream: true },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "Fail".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/Fail".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "StreamFail".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/StreamFail".to_string(), client_stream: false, server_stream: true },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "EchoMeta".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/EchoMeta".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "Big".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/Big".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "FailDetails".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/FailDetails".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "StreamFailDetails".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/StreamFailDetails".to_string(), client_stream: false, server_stream: true },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "EchoTrailer".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/EchoTrailer".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "CountTrailer".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/CountTrailer".to_string(), client_stream: false, server_stream: true },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "EchoBytes".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/EchoBytes".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "Sleep".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/Sleep".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "Empty".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/Empty".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "easyrpc.conformance.v1.ConformanceService".to_string(), name: "BigStream".to_string(), path: "/easyrpc.conformance.v1.ConformanceService/BigStream".to_string(), client_stream: false, server_stream: true },
  ]
}
