// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EchoRequest {
    #[prost(string, tag="1")]
    pub input: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EchoResponse {
    #[prost(string, tag="1")]
    pub output: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CountRequest {
    #[prost(int32, tag="1")]
    pub count: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CountResponse {
    #[prost(int32, tag="1")]
    pub index: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FailRequest {
    #[prost(string, tag="1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FailResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamFailRequest {
    #[prost(int32, tag = "1")]
    pub emit_before: i32,
    #[prost(int32, tag = "2")]
    pub code: i32,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StreamFailResponse {
    #[prost(int32, tag = "1")]
    pub index: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EchoMetaRequest {
    #[prost(string, tag = "1")]
    pub input: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EchoMetaResponse {
    #[prost(string, tag = "1")]
    pub input: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "2")]
    pub meta: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BigRequest {
    #[prost(int32, tag = "1")]
    pub size: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BigResponse {
    #[prost(int32, tag = "1")]
    pub size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FailDetailsRequest {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub detail_type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub detail_text: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FailDetailsResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamFailDetailsRequest {
    #[prost(int32, tag = "1")]
    pub emit_before: i32,
    #[prost(int32, tag = "2")]
    pub code: i32,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub detail_type: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub detail_text: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StreamFailDetailsResponse {
    #[prost(int32, tag = "1")]
    pub index: i32,
}
// @@protoc_insertion_point(module)
