// Code generated by protoc-gen-easyrpc-rust. DO NOT EDIT.
pub fn method_specs() -> Vec<crate::protocol::MethodSpec> {
  vec![
  crate::protocol::MethodSpec { service: "connectrpc.conformance.v1.ConformanceService".to_string(), name: "Unary".to_string(), path: "/connectrpc.conformance.v1.ConformanceService/Unary".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "connectrpc.conformance.v1.ConformanceService".to_string(), name: "ServerStream".to_string(), path: "/connectrpc.conformance.v1.ConformanceService/ServerStream".to_string(), client_stream: false, server_stream: true },
  crate::protocol::MethodSpec { service: "connectrpc.conformance.v1.ConformanceService".to_string(), name: "ClientStream".to_string(), path: "/connectrpc.conformance.v1.ConformanceService/ClientStream".to_string(), client_stream: true, server_stream: false },
  crate::protocol::MethodSpec { service: "connectrpc.conformance.v1.ConformanceService".to_string(), name: "BidiStream".to_string(), path: "/connectrpc.conformance.v1.ConformanceService/BidiStream".to_string(), client_stream: true, server_stream: true },
  crate::protocol::MethodSpec { service: "connectrpc.conformance.v1.ConformanceService".to_string(), name: "Unimplemented".to_string(), path: "/connectrpc.conformance.v1.ConformanceService/Unimplemented".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "connectrpc.conformance.v1.ConformanceService".to_string(), name: "IdempotentUnary".to_string(), path: "/connectrpc.conformance.v1.ConformanceService/IdempotentUnary".to_string(), client_stream: false, server_stream: false },
  ]
}
