// @generated
// This file is @generated by prost-build.
/// Config defines the configuration for running conformance tests.
/// This enumerates all of the "flavors" of the test suite to run.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Config {
    /// The features supported by the client or server under test.
    /// This is used to filter the set of test cases that are run.
    /// If absent, an empty message is used. See Features for more
    /// on how empty/absent fields are interpreted.
    #[prost(message, optional, tag = "1")]
    pub features: ::core::option::Option<Features>,
    /// This can indicate additional permutations that are supported
    /// that might otherwise be excluded based on the above features.
    #[prost(message, repeated, tag = "2")]
    pub include_cases: ::prost::alloc::vec::Vec<ConfigCase>,
    /// This can indicates permutations that are not supported even
    /// though their support might be implied by the above features.
    #[prost(message, repeated, tag = "3")]
    pub exclude_cases: ::prost::alloc::vec::Vec<ConfigCase>,
}
/// Features define the feature set that a client or server supports. They are
/// used to determine the server configurations and test cases that
/// will be run. They are defined in YAML files and are specified as part of the
/// --conf flag to the test runner.
///
/// TODO: we could probably model some of the constraints on what are valid vs.
///        invalid (i.e. conflicting/impossible) features using protovalidate rules
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Features {
    /// Supported HTTP versions.
    /// If empty, HTTP 1.1 and HTTP/2 are assumed.
    #[prost(enumeration = "HttpVersion", repeated, tag = "1")]
    pub versions: ::prost::alloc::vec::Vec<i32>,
    /// Supported protocols.
    /// If empty, all three are assumed: Connect, gRPC, and gRPC-Web.
    #[prost(enumeration = "Protocol", repeated, tag = "2")]
    pub protocols: ::prost::alloc::vec::Vec<i32>,
    /// Supported codecs.
    /// If empty, "proto" and "json" are assumed.
    #[prost(enumeration = "Codec", repeated, tag = "3")]
    pub codecs: ::prost::alloc::vec::Vec<i32>,
    /// Supported compression algorithms.
    /// If empty, "identity" and "gzip" are assumed.
    #[prost(enumeration = "Compression", repeated, tag = "4")]
    pub compressions: ::prost::alloc::vec::Vec<i32>,
    /// Supported stream types.
    /// If empty, all stream types are assumed. This is usually for
    /// clients, since some client environments may not be able to
    /// support certain kinds of streaming operations, especially
    /// bidirectional streams.
    #[prost(enumeration = "StreamType", repeated, tag = "5")]
    pub stream_types: ::prost::alloc::vec::Vec<i32>,
    /// Whether H2C (unencrypted, non-TLS HTTP/2 over cleartext) is supported.
    /// If absent, true is assumed.
    #[prost(bool, optional, tag = "6")]
    pub supports_h2c: ::core::option::Option<bool>,
    /// Whether TLS is supported.
    /// If absent, true is assumed.
    #[prost(bool, optional, tag = "7")]
    pub supports_tls: ::core::option::Option<bool>,
    /// Whether the client supports TLS certificates.
    /// If absent, false is assumed. This should not be set if
    /// supports_tls is false.
    #[prost(bool, optional, tag = "8")]
    pub supports_tls_client_certs: ::core::option::Option<bool>,
    /// Whether trailers are supported.
    /// If absent, true is assumed. If false, implies that gRPC protocol is not allowed.
    #[prost(bool, optional, tag = "9")]
    pub supports_trailers: ::core::option::Option<bool>,
    /// Whether half duplex bidi streams are supported over HTTP/1.1.
    /// If absent, false is assumed.
    #[prost(bool, optional, tag = "10")]
    pub supports_half_duplex_bidi_over_http1: ::core::option::Option<bool>,
    /// Whether Connect via GET is supported.
    /// If absent, true is assumed.
    #[prost(bool, optional, tag = "11")]
    pub supports_connect_get: ::core::option::Option<bool>,
    /// Whether a message receive limit is supported.
    /// If absent, true is assumed.
    #[prost(bool, optional, tag = "12")]
    pub supports_message_receive_limit: ::core::option::Option<bool>,
}
/// ConfigCase represents a single resolved configuration case. When tests are
/// run, the Config and the supported features therein are used to compute all
/// of the cases relevant to the implementation under test. These configuration
/// cases are then used to select which test cases are applicable.
///
/// TODO: we could probably model some of the constraints on what is a valid
///        vs. invalid config case using protovalidate rules
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfigCase {
    /// If unspecified, indicates cases for all versions.
    #[prost(enumeration = "HttpVersion", tag = "1")]
    pub version: i32,
    /// If unspecified, indicates cases for all protocols.
    #[prost(enumeration = "Protocol", tag = "2")]
    pub protocol: i32,
    /// If unspecified, indicates cases for all codecs.
    #[prost(enumeration = "Codec", tag = "3")]
    pub codec: i32,
    /// If unspecified, indicates cases for all compression algorithms.
    #[prost(enumeration = "Compression", tag = "4")]
    pub compression: i32,
    /// If unspecified, indicates cases for all stream types.
    #[prost(enumeration = "StreamType", tag = "5")]
    pub stream_type: i32,
    /// If absent, indicates cases for plaintext (no TLS) but also for
    /// TLS if features indicate that TLS is supported.
    #[prost(bool, optional, tag = "6")]
    pub use_tls: ::core::option::Option<bool>,
    /// If absent, indicates cases without client certs but also cases
    /// that use client certs if features indicate they are supported.
    #[prost(bool, optional, tag = "7")]
    pub use_tls_client_certs: ::core::option::Option<bool>,
    /// If absent, indicates cases that do not test message receive
    /// limits but also cases that do test message receive limits if
    /// features indicate they are supported.
    #[prost(bool, optional, tag = "8")]
    pub use_message_receive_limit: ::core::option::Option<bool>,
}
/// TLSCreds represents credentials for TLS. It includes both a
/// certificate and corresponding private key. Both are encoded
/// in PEM format.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TlsCreds {
    #[prost(bytes = "vec", tag = "1")]
    pub cert: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HttpVersion {
    Unspecified = 0,
    HttpVersion1 = 1,
    HttpVersion2 = 2,
    HttpVersion3 = 3,
}
impl HttpVersion {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "HTTP_VERSION_UNSPECIFIED",
            Self::HttpVersion1 => "HTTP_VERSION_1",
            Self::HttpVersion2 => "HTTP_VERSION_2",
            Self::HttpVersion3 => "HTTP_VERSION_3",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HTTP_VERSION_UNSPECIFIED" => Some(Self::Unspecified),
            "HTTP_VERSION_1" => Some(Self::HttpVersion1),
            "HTTP_VERSION_2" => Some(Self::HttpVersion2),
            "HTTP_VERSION_3" => Some(Self::HttpVersion3),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Protocol {
    Unspecified = 0,
    Connect = 1,
    Grpc = 2,
    /// TODO: Support add'l protocols:
    /// PROTOCOL_GRPC_WEB_TEXT = 4;
    /// PROTOCOL_REST_TRANSCODING = 5;
    GrpcWeb = 3,
}
impl Protocol {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROTOCOL_UNSPECIFIED",
            Self::Connect => "PROTOCOL_CONNECT",
            Self::Grpc => "PROTOCOL_GRPC",
            Self::GrpcWeb => "PROTOCOL_GRPC_WEB",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROTOCOL_UNSPECIFIED" => Some(Self::Unspecified),
            "PROTOCOL_CONNECT" => Some(Self::Connect),
            "PROTOCOL_GRPC" => Some(Self::Grpc),
            "PROTOCOL_GRPC_WEB" => Some(Self::GrpcWeb),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Codec {
    Unspecified = 0,
    Proto = 1,
    Json = 2,
    /// not used; will be ignored
    #[deprecated]
    Text = 3,
}
impl Codec {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CODEC_UNSPECIFIED",
            Self::Proto => "CODEC_PROTO",
            Self::Json => "CODEC_JSON",
            #[allow(deprecated)]
            Self::Text => "CODEC_TEXT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CODEC_UNSPECIFIED" => Some(Self::Unspecified),
            "CODEC_PROTO" => Some(Self::Proto),
            "CODEC_JSON" => Some(Self::Json),
            "CODEC_TEXT" => Some(#[allow(deprecated)] Self::Text),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Compression {
    Unspecified = 0,
    Identity = 1,
    Gzip = 2,
    Br = 3,
    Zstd = 4,
    Deflate = 5,
    Snappy = 6,
}
impl Compression {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COMPRESSION_UNSPECIFIED",
            Self::Identity => "COMPRESSION_IDENTITY",
            Self::Gzip => "COMPRESSION_GZIP",
            Self::Br => "COMPRESSION_BR",
            Self::Zstd => "COMPRESSION_ZSTD",
            Self::Deflate => "COMPRESSION_DEFLATE",
            Self::Snappy => "COMPRESSION_SNAPPY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMPRESSION_UNSPECIFIED" => Some(Self::Unspecified),
            "COMPRESSION_IDENTITY" => Some(Self::Identity),
            "COMPRESSION_GZIP" => Some(Self::Gzip),
            "COMPRESSION_BR" => Some(Self::Br),
            "COMPRESSION_ZSTD" => Some(Self::Zstd),
            "COMPRESSION_DEFLATE" => Some(Self::Deflate),
            "COMPRESSION_SNAPPY" => Some(Self::Snappy),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StreamType {
    Unspecified = 0,
    Unary = 1,
    ClientStream = 2,
    ServerStream = 3,
    HalfDuplexBidiStream = 4,
    FullDuplexBidiStream = 5,
}
impl StreamType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STREAM_TYPE_UNSPECIFIED",
            Self::Unary => "STREAM_TYPE_UNARY",
            Self::ClientStream => "STREAM_TYPE_CLIENT_STREAM",
            Self::ServerStream => "STREAM_TYPE_SERVER_STREAM",
            Self::HalfDuplexBidiStream => "STREAM_TYPE_HALF_DUPLEX_BIDI_STREAM",
            Self::FullDuplexBidiStream => "STREAM_TYPE_FULL_DUPLEX_BIDI_STREAM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STREAM_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "STREAM_TYPE_UNARY" => Some(Self::Unary),
            "STREAM_TYPE_CLIENT_STREAM" => Some(Self::ClientStream),
            "STREAM_TYPE_SERVER_STREAM" => Some(Self::ServerStream),
            "STREAM_TYPE_HALF_DUPLEX_BIDI_STREAM" => Some(Self::HalfDuplexBidiStream),
            "STREAM_TYPE_FULL_DUPLEX_BIDI_STREAM" => Some(Self::FullDuplexBidiStream),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Code {
    Unspecified = 0,
    Canceled = 1,
    Unknown = 2,
    InvalidArgument = 3,
    DeadlineExceeded = 4,
    NotFound = 5,
    AlreadyExists = 6,
    PermissionDenied = 7,
    ResourceExhausted = 8,
    FailedPrecondition = 9,
    Aborted = 10,
    OutOfRange = 11,
    Unimplemented = 12,
    Internal = 13,
    Unavailable = 14,
    DataLoss = 15,
    Unauthenticated = 16,
}
impl Code {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CODE_UNSPECIFIED",
            Self::Canceled => "CODE_CANCELED",
            Self::Unknown => "CODE_UNKNOWN",
            Self::InvalidArgument => "CODE_INVALID_ARGUMENT",
            Self::DeadlineExceeded => "CODE_DEADLINE_EXCEEDED",
            Self::NotFound => "CODE_NOT_FOUND",
            Self::AlreadyExists => "CODE_ALREADY_EXISTS",
            Self::PermissionDenied => "CODE_PERMISSION_DENIED",
            Self::ResourceExhausted => "CODE_RESOURCE_EXHAUSTED",
            Self::FailedPrecondition => "CODE_FAILED_PRECONDITION",
            Self::Aborted => "CODE_ABORTED",
            Self::OutOfRange => "CODE_OUT_OF_RANGE",
            Self::Unimplemented => "CODE_UNIMPLEMENTED",
            Self::Internal => "CODE_INTERNAL",
            Self::Unavailable => "CODE_UNAVAILABLE",
            Self::DataLoss => "CODE_DATA_LOSS",
            Self::Unauthenticated => "CODE_UNAUTHENTICATED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CODE_UNSPECIFIED" => Some(Self::Unspecified),
            "CODE_CANCELED" => Some(Self::Canceled),
            "CODE_UNKNOWN" => Some(Self::Unknown),
            "CODE_INVALID_ARGUMENT" => Some(Self::InvalidArgument),
            "CODE_DEADLINE_EXCEEDED" => Some(Self::DeadlineExceeded),
            "CODE_NOT_FOUND" => Some(Self::NotFound),
            "CODE_ALREADY_EXISTS" => Some(Self::AlreadyExists),
            "CODE_PERMISSION_DENIED" => Some(Self::PermissionDenied),
            "CODE_RESOURCE_EXHAUSTED" => Some(Self::ResourceExhausted),
            "CODE_FAILED_PRECONDITION" => Some(Self::FailedPrecondition),
            "CODE_ABORTED" => Some(Self::Aborted),
            "CODE_OUT_OF_RANGE" => Some(Self::OutOfRange),
            "CODE_UNIMPLEMENTED" => Some(Self::Unimplemented),
            "CODE_INTERNAL" => Some(Self::Internal),
            "CODE_UNAVAILABLE" => Some(Self::Unavailable),
            "CODE_DATA_LOSS" => Some(Self::DataLoss),
            "CODE_UNAUTHENTICATED" => Some(Self::Unauthenticated),
            _ => None,
        }
    }
}
/// A definition of a response to be sent from a single-response endpoint.
/// Can be used to define a response for unary or client-streaming calls.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnaryResponseDefinition {
    /// Response headers to send
    #[prost(message, repeated, tag = "1")]
    pub response_headers: ::prost::alloc::vec::Vec<Header>,
    /// Response trailers to send - together with the error if present
    #[prost(message, repeated, tag = "4")]
    pub response_trailers: ::prost::alloc::vec::Vec<Header>,
    /// Wait this many milliseconds before sending a response message
    #[prost(uint32, tag = "6")]
    pub response_delay_ms: u32,
    /// This field is only used by the reference server. If you are implementing a
    /// server under test, you can ignore this field or respond with an error if the
    /// server receives a request where it is set.
    ///
    /// For test definitions, this field should be used instead of the above fields.
    #[prost(message, optional, tag = "5")]
    pub raw_response: ::core::option::Option<RawHttpResponse>,
    #[prost(oneof = "unary_response_definition::Response", tags = "2, 3")]
    pub response: ::core::option::Option<unary_response_definition::Response>,
}
/// Nested message and enum types in `UnaryResponseDefinition`.
pub mod unary_response_definition {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        /// Response data to send
        #[prost(bytes, tag = "2")]
        ResponseData(::prost::alloc::vec::Vec<u8>),
        /// Error to raise instead of response message
        /// Servers should build a RequestInfo and append it to the details of the
        /// requested error.
        #[prost(message, tag = "3")]
        Error(super::Error),
    }
}
/// A definition of responses to be sent from a streaming endpoint.
/// Can be used to define responses for server-streaming or bidi-streaming calls.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamResponseDefinition {
    /// Response headers to send
    #[prost(message, repeated, tag = "1")]
    pub response_headers: ::prost::alloc::vec::Vec<Header>,
    /// Response data to send
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub response_data: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Wait this many milliseconds before sending each response message
    #[prost(uint32, tag = "3")]
    pub response_delay_ms: u32,
    /// Optional error to raise, but only after sending any response messages.
    /// In the event an immediate error is thrown before any responses are sent,
    /// (i.e. the equivalent of a trailers-only response), then servers should
    /// build a RequestInfo message with available information and append that to
    /// the error details.
    #[prost(message, optional, tag = "4")]
    pub error: ::core::option::Option<Error>,
    /// Response trailers to send - together with the error if present
    #[prost(message, repeated, tag = "5")]
    pub response_trailers: ::prost::alloc::vec::Vec<Header>,
    /// This field is only used by the reference server. If you are implementing a
    /// server under test, you can ignore this field or respond with an error if the
    /// server receives a request where it is set.
    ///
    /// For test definitions, this field should be used instead of the above fields.
    #[prost(message, optional, tag = "6")]
    pub raw_response: ::core::option::Option<RawHttpResponse>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnaryRequest {
    /// The response definition which should be returned in the conformance payload
    #[prost(message, optional, tag = "1")]
    pub response_definition: ::core::option::Option<UnaryResponseDefinition>,
    /// Additional data. Only used to pad the request size to test large request messages.
    #[prost(bytes = "vec", tag = "2")]
    pub request_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnaryResponse {
    /// The conformance payload to respond with.
    #[prost(message, optional, tag = "1")]
    pub payload: ::core::option::Option<ConformancePayload>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IdempotentUnaryRequest {
    /// The response definition which should be returned in the conformance payload
    #[prost(message, optional, tag = "1")]
    pub response_definition: ::core::option::Option<UnaryResponseDefinition>,
    /// Additional data. Only used to pad the request size to test large request messages.
    #[prost(bytes = "vec", tag = "2")]
    pub request_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IdempotentUnaryResponse {
    /// The conformance payload to respond with.
    #[prost(message, optional, tag = "1")]
    pub payload: ::core::option::Option<ConformancePayload>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerStreamRequest {
    /// The response definition which should be returned in the conformance payload.
    #[prost(message, optional, tag = "1")]
    pub response_definition: ::core::option::Option<StreamResponseDefinition>,
    /// Additional data. Only used to pad the request size to test large request messages.
    #[prost(bytes = "vec", tag = "2")]
    pub request_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerStreamResponse {
    /// The conformance payload to respond with
    #[prost(message, optional, tag = "1")]
    pub payload: ::core::option::Option<ConformancePayload>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientStreamRequest {
    /// Tells the server how to reply once all client messages are
    /// complete. Required in the first message in the stream, but
    /// should be ignored in subsequent messages.
    #[prost(message, optional, tag = "1")]
    pub response_definition: ::core::option::Option<UnaryResponseDefinition>,
    /// Additional data for subsequent messages in the stream. Also
    /// used to pad the request size to test large request messages.
    #[prost(bytes = "vec", tag = "2")]
    pub request_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientStreamResponse {
    /// The conformance payload to respond with
    #[prost(message, optional, tag = "1")]
    pub payload: ::core::option::Option<ConformancePayload>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BidiStreamRequest {
    /// Tells the server how to reply; required in the first message
    /// in the stream. Should be ignored in subsequent messages.
    #[prost(message, optional, tag = "1")]
    pub response_definition: ::core::option::Option<StreamResponseDefinition>,
    /// Tells the server whether it should wait for each request
    /// before sending a response.
    ///
    /// If true, it indicates the server should effectively interleave the
    /// stream so messages are sent in request->response pairs.
    ///
    /// If false, then the response stream will be sent once all request messages
    /// are finished sending with the only delays between messages
    /// being the optional fixed milliseconds defined in the response
    /// definition.
    ///
    /// This field is only relevant in the first message in the stream
    /// and should be ignored in subsequent messages.
    #[prost(bool, tag = "2")]
    pub full_duplex: bool,
    /// Additional data for subsequent messages in the stream. Also
    /// used to pad the request size to test large request messages.
    #[prost(bytes = "vec", tag = "3")]
    pub request_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BidiStreamResponse {
    /// The conformance payload to respond with
    #[prost(message, optional, tag = "1")]
    pub payload: ::core::option::Option<ConformancePayload>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnimplementedRequest {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnimplementedResponse {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConformancePayload {
    /// Any response data specified in the response definition to the server should be
    /// echoed back here.
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Echoes back information about the request stream observed so far.
    #[prost(message, optional, tag = "2")]
    pub request_info: ::core::option::Option<conformance_payload::RequestInfo>,
}
/// Nested message and enum types in `ConformancePayload`.
pub mod conformance_payload {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RequestInfo {
        /// The server echos back the request headers it observed here.
        #[prost(message, repeated, tag = "1")]
        pub request_headers: ::prost::alloc::vec::Vec<super::Header>,
        /// The timeout observed that was included in the request. Other timeouts use a
        /// type of uint32, but we want to be lenient here to allow whatever value the RPC
        /// server observes, even if it's outside the range of uint32.
        #[prost(int64, optional, tag = "2")]
        pub timeout_ms: ::core::option::Option<i64>,
        /// The server should echo back all requests received.
        /// For unary and server-streaming requests, this should always contain a single request
        /// For client-streaming and half-duplex bidi-streaming, this should contain
        /// all client requests in the order received and be present in each response.
        /// For full-duplex bidirectional-streaming, this should contain all requests in the order
        /// they were received since the last sent response.
        #[prost(message, repeated, tag = "3")]
        pub requests: ::prost::alloc::vec::Vec<::prost_types::Any>,
        /// If present, the request used the Connect protocol and a GET method. This
        /// captures other relevant information about the request. If a server implementation
        /// is unable to populate this (due to the server framework not exposing all of these
        /// details to application code), it may be an empty message. This implies that the
        /// server framework, at a minimum, at least expose to application code whether the
        /// request used GET vs. POST.
        #[prost(message, optional, tag = "4")]
        pub connect_get_info: ::core::option::Option<ConnectGetInfo>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ConnectGetInfo {
        /// The query params observed in the request URL.
        #[prost(message, repeated, tag = "1")]
        pub query_params: ::prost::alloc::vec::Vec<super::Header>,
    }
}
/// An error definition used for specifying a desired error response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Error {
    /// The error code.
    /// For a list of Connect error codes see: <https://connectrpc.com/docs/protocol#error-codes>
    #[prost(enumeration = "Code", tag = "1")]
    pub code: i32,
    /// If this value is absent in a test case response definition, the contents of the
    /// actual error message will not be checked. This is useful for certain kinds of
    /// error conditions where the exact message to be used is not specified, only the
    /// code.
    #[prost(string, optional, tag = "2")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
    /// Errors in Connect and gRPC protocols can have arbitrary messages
    /// attached to them, which are known as error details.
    #[prost(message, repeated, tag = "3")]
    pub details: ::prost::alloc::vec::Vec<::prost_types::Any>,
}
/// A tuple of name and values (ASCII) for a header or trailer entry.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Header {
    /// Header/trailer name (key).
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Header/trailer value. This is repeated to explicitly support headers and
    /// trailers where a key is repeated. In such a case, these values must be in
    /// the same order as which values appeared in the header or trailer block.
    #[prost(string, repeated, tag = "2")]
    pub value: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// RawHTTPRequest models a raw HTTP request. This can be used to craft
/// custom requests with odd properties (including certain kinds of
/// malformed requests) to test edge cases in servers.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RawHttpRequest {
    /// The HTTP verb (i.e. GET , POST).
    #[prost(string, tag = "1")]
    pub verb: ::prost::alloc::string::String,
    /// The URI to send the request to.
    #[prost(string, tag = "2")]
    pub uri: ::prost::alloc::string::String,
    /// Any headers to set on the request.
    #[prost(message, repeated, tag = "3")]
    pub headers: ::prost::alloc::vec::Vec<Header>,
    /// These query params will be encoded and added to the uri before
    /// the request is sent.
    #[prost(message, repeated, tag = "4")]
    pub raw_query_params: ::prost::alloc::vec::Vec<Header>,
    /// This provides an easier way to define a complex binary query param
    /// than having to write literal base64-encoded bytes in raw_query_params.
    #[prost(message, repeated, tag = "5")]
    pub encoded_query_params: ::prost::alloc::vec::Vec<raw_http_request::EncodedQueryParam>,
    #[prost(oneof = "raw_http_request::Body", tags = "6, 7")]
    pub body: ::core::option::Option<raw_http_request::Body>,
}
/// Nested message and enum types in `RawHTTPRequest`.
pub mod raw_http_request {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct EncodedQueryParam {
        /// Query param name.
        #[prost(string, tag = "1")]
        pub name: ::prost::alloc::string::String,
        /// Query param value.
        #[prost(message, optional, tag = "2")]
        pub value: ::core::option::Option<super::MessageContents>,
        /// If true, the message contents will be base64-encoded and the
        /// resulting string used as the query parameter value.
        #[prost(bool, tag = "3")]
        pub base64_encode: bool,
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        /// The body is a single message.
        #[prost(message, tag = "6")]
        Unary(super::MessageContents),
        /// The body is a stream, encoded using a five-byte
        /// prefix before each item in the stream.
        #[prost(message, tag = "7")]
        Stream(super::StreamContents),
    }
}
/// MessageContents represents a message in a request body.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageContents {
    /// If specified and not identity, the above data will be
    /// compressed using the given algorithm.
    #[prost(enumeration = "Compression", tag = "4")]
    pub compression: i32,
    /// The message data can be defined in one of three ways.
    #[prost(oneof = "message_contents::Data", tags = "1, 2, 3")]
    pub data: ::core::option::Option<message_contents::Data>,
}
/// Nested message and enum types in `MessageContents`.
pub mod message_contents {
    /// The message data can be defined in one of three ways.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        /// Arbitrary bytes.
        #[prost(bytes, tag = "1")]
        Binary(::prost::alloc::vec::Vec<u8>),
        /// Arbitrary text.
        #[prost(string, tag = "2")]
        Text(::prost::alloc::string::String),
        /// An actual message. The message inside the Any will be
        /// serialized to the protobuf binary formats, and the
        /// resulting bytes will be the contents.
        #[prost(message, tag = "3")]
        BinaryMessage(::prost_types::Any),
    }
}
/// StreamContents represents a sequence of messages in a request body.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamContents {
    /// The messages in the stream.
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<stream_contents::StreamItem>,
}
/// Nested message and enum types in `StreamContents`.
pub mod stream_contents {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct StreamItem {
        /// must be in the range 0 to 255.
        #[prost(uint32, tag = "1")]
        pub flags: u32,
        /// if absent use actual length of payload
        #[prost(uint32, optional, tag = "2")]
        pub length: ::core::option::Option<u32>,
        #[prost(message, optional, tag = "3")]
        pub payload: ::core::option::Option<super::MessageContents>,
    }
}
/// RawHTTPResponse models a raw HTTP response. This can be used to craft
/// custom responses with odd properties (including certain kinds of
/// malformed responses) to test edge cases in clients.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RawHttpResponse {
    /// If status code is not specified, it will default to a 200 response code.
    #[prost(uint32, tag = "1")]
    pub status_code: u32,
    /// Headers to be set on the response.
    #[prost(message, repeated, tag = "2")]
    pub headers: ::prost::alloc::vec::Vec<Header>,
    /// Trailers to be set on the response.
    #[prost(message, repeated, tag = "5")]
    pub trailers: ::prost::alloc::vec::Vec<Header>,
    #[prost(oneof = "raw_http_response::Body", tags = "3, 4")]
    pub body: ::core::option::Option<raw_http_response::Body>,
}
/// Nested message and enum types in `RawHTTPResponse`.
pub mod raw_http_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        /// The body is a single message.
        #[prost(message, tag = "3")]
        Unary(super::MessageContents),
        /// The body is a stream, encoded using a five-byte
        /// prefix before each item in the stream.
        #[prost(message, tag = "4")]
        Stream(super::StreamContents),
    }
}
/// Describes one configuration for an RPC server. The server is
/// expected to expose the connectrpc.conformance.v1.ConformanceService
/// RPC service. The configuration does not include a port. The
/// process should pick an available port, which is typically
/// done by using port zero (0) when creating a network listener
/// so that the OS selects an available ephemeral port.
///
/// These properties are read from stdin. Once the server is
/// listening, details about the server, in the form of a
/// ServerCompatResponse, are written to stdout.
///
/// Each test process is expected to start only one RPC server.
/// When testing multiple configurations, multiple test processes
/// will be started, each with different properties.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerCompatRequest {
    /// Signals to the server that it must support at least this protocol. Note
    /// that it is fine to support others.
    /// For example if `PROTOCOL_CONNECT` is specified, the server _must_ support
    /// at least Connect, but _may_ also support gRPC or gRPC-web.
    #[prost(enumeration = "Protocol", tag = "1")]
    pub protocol: i32,
    /// Signals to the server the minimum HTTP version to support. As with
    /// `protocol`, it is fine to support other versions. For example, if
    /// `HTTP_VERSION_2` is specified, the server _must_ support HTTP/2, but _may_ also
    /// support HTTP/1.1 or HTTP/3.
    #[prost(enumeration = "HttpVersion", tag = "2")]
    pub http_version: i32,
    /// If true, generate a certificate that clients will be configured to trust
    /// when connecting and return it in the `pem_cert` field of the `ServerCompatResponse`.
    /// The certificate can be any TLS certificate where the subject matches the
    /// value sent back in the `host` field of the `ServerCompatResponse`.
    /// Self-signed certificates (and `localhost` as the subject) are allowed.
    /// If false, the server should not use TLS and instead use
    /// a plain-text/unencrypted socket.
    #[prost(bool, tag = "4")]
    pub use_tls: bool,
    /// If non-empty, the clients will use certificates to authenticate
    /// themselves. This value is a PEM-encoded cert that should be
    /// trusted by the server. When non-empty, the server should require
    /// that clients provide certificates and they should validate that
    /// the certificate presented is valid.
    ///
    /// This will always be empty if use_tls is false.
    #[prost(bytes = "vec", tag = "5")]
    pub client_tls_cert: ::prost::alloc::vec::Vec<u8>,
    /// If non-zero, indicates the maximum size in bytes for a message.
    /// If the client sends anything larger, the server should reject it.
    #[prost(uint32, tag = "6")]
    pub message_receive_limit: u32,
    /// If use_tls is true, this provides details for a self-signed TLS
    /// cert that the server may use.
    ///
    /// The provided certificate is only good for loopback communication:
    /// it uses "localhost" and "127.0.0.1" as the IP and DNS names in
    /// the certificate's subject. If the server needs a different subject
    /// or the client is in an environment where configuring trust of a
    /// self-signed certificate is difficult or infeasible.
    ///
    /// If the server implementation chooses to use these credentials,
    /// it must echo back the certificate in the ServerCompatResponse and
    /// should also leave the host field empty or explicitly set to
    /// "127.0.0.1".
    ///
    /// If it chooses to use a different certificate and key, it must send
    /// back the corresponding certificate in the ServerCompatResponse.
    #[prost(message, optional, tag = "7")]
    pub server_creds: ::core::option::Option<TlsCreds>,
}
/// The outcome of one ServerCompatRequest.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerCompatResponse {
    /// The host where the server is running. This should usually be `127.0.0.1`,
    /// unless your program actually starts a remote server to which the client
    /// should connect.
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    /// The port where the server is listening.
    #[prost(uint32, tag = "2")]
    pub port: u32,
    /// The TLS certificate, in PEM format, if `use_tls` was set
    /// to `true`. Clients will verify this certificate when connecting via TLS.
    /// If `use_tls` was set to `false`, this should always be empty.
    #[prost(bytes = "vec", tag = "3")]
    pub pem_cert: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
