//! Descriptor pools for the proto3 JSON codec (prost-reflect).
//!
//! pbjson cannot emit the special proto3 JSON encoding of `google.protobuf.Any`
//! (the `@type` form), which Connect requires. prost-reflect handles the whole
//! proto3 JSON mapping (including `Any`, WKTs, and field-name rules), so the
//! JSON codec routes through a `DynamicMessage` built from these pools.
//!
//! The pools are built once from the committed descriptor sets (generated by
//! `tool/gen-messages.sh`). Static messages are converted to/from dynamic form
//! via their wire bytes, keyed by `prost::Name::full_name()`.

use prost_reflect::DescriptorPool;
use std::sync::OnceLock;

static OFFICIAL: OnceLock<DescriptorPool> = OnceLock::new();
static CONFORMANCE: OnceLock<DescriptorPool> = OnceLock::new();

/// The official ConnectRPC conformance service descriptor pool.
pub fn official_pool() -> &'static DescriptorPool {
    OFFICIAL.get_or_init(|| {
        DescriptorPool::decode(include_bytes!("descriptors/official.bin").as_slice())
            .expect("official descriptor pool")
    })
}

/// The easy-rpc conformance service descriptor pool.
pub fn conformance_pool() -> &'static DescriptorPool {
    CONFORMANCE.get_or_init(|| {
        DescriptorPool::decode(include_bytes!("descriptors/conformance.bin").as_slice())
            .expect("conformance descriptor pool")
    })
}

/// Find a message descriptor by full name across both pools.
pub fn descriptor_for(full_name: &str) -> Option<prost_reflect::MessageDescriptor> {
    official_pool()
        .get_message_by_name(full_name)
        .or_else(|| conformance_pool().get_message_by_name(full_name))
}
